
import '../../../../models/spending_model.dart';

List<SpendingModel> listSpending = [
  SpendingModel(iconPath: 'assets/images/food_icon.png',title: 'Thực phẩm'),
  SpendingModel(iconPath: 'assets/images/clothes_icon.png',title: 'Quần áo'),
  SpendingModel(iconPath: 'assets/images/breakfast_icon.png',title: 'Ăn Sáng'),
  SpendingModel(iconPath: 'assets/images/seafood_icon.png',title: 'Hải sản'),
  SpendingModel(iconPath: 'assets/images/vegetable_icon.png',title: 'Rau củ'),
  SpendingModel(iconPath: 'assets/images/rent_icon.png',title: 'Thuê nhà'),
  SpendingModel(iconPath: 'assets/images/gas_icon.png',title: 'Gas'),
  SpendingModel(iconPath: 'assets/images/market_icon.png',title: 'Đi chợ'),
  SpendingModel(iconPath: 'assets/images/book_icon.png',title: 'Sách'),
  SpendingModel(iconPath: 'assets/images/entertain_icon.png',title: 'Giải trí'),
  SpendingModel(iconPath: 'assets/images/education_icon.png',title: 'Giáo dục'),
  SpendingModel(iconPath: 'assets/images/baby_icon.png',title: 'Trẻ em'),
  SpendingModel(iconPath: 'assets/images/petroleum_icon.png',title: 'Xăng dầu'),
  SpendingModel(iconPath: 'assets/images/medican_icon.png',title: 'Y tế'),
  SpendingModel(iconPath: 'assets/images/gym_icon.png',title: 'Gym'),
  SpendingModel(iconPath: 'assets/images/fruit_icon.png',title: 'Hoa quả'),
  SpendingModel(iconPath: 'assets/images/internet_icon.png',title: 'Internet'),
  SpendingModel(iconPath: 'assets/images/telephone_icon.png',title: 'Điện thoại'),
  SpendingModel(iconPath: 'assets/images/movie_icon.png',title: 'Phim ảnh'),
  SpendingModel(iconPath: 'assets/images/insect_icon.png',title: 'Côn trùng'),
  SpendingModel(iconPath: 'assets/images/spa_icon.png',title: 'Spa'),
  SpendingModel(iconPath: 'assets/images/insurance_icon.png',title: 'Bảo hiểm'),
  SpendingModel(iconPath: 'assets/images/beer_icon.png',title: 'Bia'),
  SpendingModel(iconPath: 'assets/images/haircut_icon.png',title: 'Cắt tóc'),
  SpendingModel(iconPath: 'assets/images/bonsai_icon.png',title: 'Cây cảnh'),
  SpendingModel(iconPath: 'assets/images/cocktail_icon.png',title: 'Cocktail'),
  SpendingModel(iconPath: 'assets/images/coffee_icon.png',title: 'Cà phê'),
  SpendingModel(iconPath: 'assets/images/tool_icon.png',title: 'Công cụ'),
  SpendingModel(iconPath: 'assets/images/tourism_icon.png',title: 'Du lịch'),
  SpendingModel(iconPath: 'assets/images/flower_icon.png',title: 'Hoa'),
  SpendingModel(iconPath: 'assets/images/computer_icon.png',title: 'Máy tính'),
  SpendingModel(iconPath: 'assets/images/music_icon.png',title: 'Âm nhạc'),
  SpendingModel(iconPath: 'assets/images/restaurant_icon.png',title: 'Nhà hàng'),
  SpendingModel(iconPath: 'assets/images/present_icon.png',title: 'Quà tặng'),
  SpendingModel(iconPath: 'assets/images/waste_icon.png',title: 'Rác thải'),
  SpendingModel(iconPath: 'assets/images/bread_icon.png',title: 'Bánh mì'),
  SpendingModel(iconPath: 'assets/images/pet_icon.png',title: 'Thú cưng'),
  SpendingModel(iconPath: 'assets/images/medicine_icon.png',title: 'Dược phẩm'),
  SpendingModel(iconPath: 'assets/images/ticket_icon.png',title: 'Vé'),
  SpendingModel(iconPath: 'assets/images/another_icon.png',title: 'Khác'),
];
