
import '../model/spending.dart';

List<Spending> listSpending = [
  Spending(iconPath: '',title: 'Thực phẩm'),
  Spending(iconPath: '',title: 'Ăn Sáng'),
  Spending(iconPath: '',title: 'Quần áo'),
  Spending(iconPath: '',title: 'Hải sản'),
  Spending(iconPath: '',title: 'Rau củ'),
  Spending(iconPath: '',title: 'Thuê nhà'),
  Spending(iconPath: '',title: 'Gas'),
  Spending(iconPath: '',title: 'Đi chợ'),
  Spending(iconPath: '',title: 'Sách'),
  Spending(iconPath: '',title: 'Giải trí'),
  Spending(iconPath: '',title: 'Giáo dục'),
  Spending(iconPath: '',title: 'Trẻ em'),
  Spending(iconPath: '',title: 'Xăng dầu'),
  Spending(iconPath: '',title: 'Y tế'),
  Spending(iconPath: '',title: 'Gym'),
  Spending(iconPath: '',title: 'Hoa quả'),
  Spending(iconPath: '',title: 'Internet'),
  Spending(iconPath: '',title: 'Điện thoại'),
  Spending(iconPath: '',title: 'Phim ảnh'),
  Spending(iconPath: '',title: 'Côn trùng'),
  Spending(iconPath: '',title: 'Spa'),
  Spending(iconPath: '',title: 'Bảo hiểm'),
  Spending(iconPath: '',title: 'Bia'),
  Spending(iconPath: '',title: 'Cắt tóc'),
  Spending(iconPath: '',title: 'Cây cảnh'),
  Spending(iconPath: '',title: 'Cocktail'),
  Spending(iconPath: '',title: 'Cà phê'),
  Spending(iconPath: '',title: 'Công cụ'),
  Spending(iconPath: '',title: 'Du lịch'),
  Spending(iconPath: '',title: 'Hoa'),
  Spending(iconPath: '',title: 'Máy tính'),
  Spending(iconPath: '',title: 'Âm nhạc'),
  Spending(iconPath: '',title: 'Nhà hàng'),
  Spending(iconPath: '',title: 'Quà tặng'),
  Spending(iconPath: '',title: 'Rác thải'),
  Spending(iconPath: '',title: 'Bánh mì'),
  Spending(iconPath: '',title: 'Thú cưng'),
  Spending(iconPath: '',title: 'Dược phẩm'),
  Spending(iconPath: '',title: 'Vé'),
  Spending(iconPath: '',title: 'Khác'),
];